export const projects = [
  {
    id: 'pavilion-high-ridge',
    place: 'High Ridge',
    region: 'Oregon',
    year: '2026',
    category: 'Residential',
    name: 'The Pavilion at High Ridge',
    image: '/src/images/projects/Pavilion.jpeg',
    alt: 'The Pavilion at High Ridge nestled into a wooded hillside',
    description: 'A low-impact pavilion shaped around a wooded hillside, where framed views and quiet transitions between inside and out make the landscape the central room.',
  },
  {
    id: 'arroyo-house',
    place: 'Santa Fe',
    region: 'New Mexico',
    year: '2018',
    category: 'Residential',
    name: 'Arroyo House',
    image: '/src/images/projects/Pavilion.jpeg',
    alt: 'A low adobe residence beside a desert arroyo in Santa Fe',
    description: 'A shaded adobe residence shaped around desert light, thermal mass, and the quiet movement of water through the site.',
  },
  {
    id: 'lakeglass-cabin',
    place: 'Traverse City',
    region: 'Michigan',
    year: '2018',
    category: 'Residential',
    name: 'Lakeglass Cabin',
    image: '/src/images/projects/Pavilion.jpeg',
    alt: 'A compact timber cabin beside an inland lake in Traverse City',
    description: 'A compact timber retreat that opens to the lake while holding close to the birch and maple forest around it.',
  },
  {
    id: 'the-brickline',
    place: 'Baltimore',
    region: 'Maryland',
    year: '2019',
    category: 'Adaptive Reuse',
    name: 'The Brickline',
    image: '/src/images/projects/Pavilion.jpeg',
    alt: 'A renovated Baltimore rowhouse with a contemporary brick addition',
    description: 'A careful rowhouse renovation pairing preserved masonry with a light-filled rear addition and planted courtyard.',
  },
  {
    id: 'palmetto-house',
    place: 'Charleston',
    region: 'South Carolina',
    year: '2019',
    category: 'Residential',
    name: 'Palmetto House',
    image: '/src/images/projects/Pavilion.jpeg',
    alt: 'A contemporary coastal house with shaded verandas in Charleston',
    description: 'A climate-responsive coastal home of shaded verandas, pale stucco, timber shutters, and live oak canopy.',
  },
  {
    id: 'mesa-arts-annex',
    place: 'Phoenix',
    region: 'Arizona',
    year: '2020',
    category: 'Cultural',
    name: 'Mesa Arts Annex',
    image: '/src/images/projects/Pavilion.jpeg',
    alt: 'A small rammed-earth arts annex in the Phoenix desert',
    description: 'A small arts center organized around a cool desert courtyard, with rammed earth and perforated shade screens.',
  },
  {
    id: 'north-loop-market',
    place: 'Minneapolis',
    region: 'Minnesota',
    year: '2020',
    category: 'Adaptive Reuse',
    name: 'North Loop Market',
    image: '/src/images/projects/Pavilion.jpeg',
    alt: 'An adaptive reuse market inside a brick warehouse in Minneapolis',
    description: 'A neighborhood market that gives a brick warehouse new life through timber stalls, shared tables, and winter light.',
  },
  {
    id: 'tidehouse',
    place: 'Provincetown',
    region: 'Massachusetts',
    year: '2021',
    category: 'Residential',
    name: 'Tidehouse',
    image: '/src/images/projects/Pavilion.jpeg',
    alt: 'A compact weathered cedar house among coastal dunes in Provincetown',
    description: 'A compact cedar house set lightly among the dunes, with a sheltered deck oriented toward the Atlantic horizon.',
  },
  {
    id: 'redbud-learning-center',
    place: 'Austin',
    region: 'Texas',
    year: '2021',
    category: 'Civic',
    name: 'Redbud Learning Center',
    image: '/src/images/projects/Pavilion.jpeg',
    alt: 'A neighborhood learning center with shaded outdoor classrooms in Austin',
    description: 'A neighborhood learning center where broad roofs and screened porches turn the outdoor classroom into the heart of the plan.',
  },
  {
    id: 'the-long-porch',
    place: 'Lexington',
    region: 'Kentucky',
    year: '2022',
    category: 'Residential',
    name: 'The Long Porch',
    image: '/src/images/projects/Pavilion.jpeg',
    alt: 'A rural retreat with a long covered porch in the Kentucky hills',
    description: 'A rural retreat grounded in local limestone, timber, and a long porch looking across the bluegrass hills.',
  },
  {
    id: 'bayou-workshop',
    place: 'New Orleans',
    region: 'Louisiana',
    year: '2022',
    category: 'Commercial',
    name: 'Bayou Workshop',
    image: '/src/images/projects/Pavilion.jpeg',
    alt: 'An elevated timber workshop in a Louisiana bayou landscape',
    description: 'An elevated timber workshop designed for shade, airflow, and a close daily relationship with the bayou landscape.',
  },
  {
    id: 'cottonwood-court',
    place: 'Denver',
    region: 'Colorado',
    year: '2023',
    category: 'Multi-family',
    name: 'Cottonwood Court',
    image: '/src/images/projects/Pavilion.jpeg',
    alt: 'A small brick courtyard housing complex in Denver',
    description: 'A modest courtyard housing complex using brick, native grasses, and shared outdoor space to build a sense of belonging.',
  },
  {
    id: 'harbor-steps',
    place: 'Cleveland',
    region: 'Ohio',
    year: '2023',
    category: 'Civic',
    name: 'Harbor Steps',
    image: '/src/images/projects/Pavilion.jpeg',
    alt: 'A timber and weathering steel waterfront pavilion in Cleveland',
    description: 'A waterfront pavilion of timber and weathering steel that makes room for gathering beside Lake Erie.',
  },
  {
    id: 'red-rock-retreat',
    place: 'Moab',
    region: 'Utah',
    year: '2024',
    category: 'Residential',
    name: 'Red Rock Retreat',
    image: '/src/images/projects/Pavilion.jpeg',
    alt: 'A minimal desert retreat beside red sandstone cliffs near Moab',
    description: 'A quiet desert retreat tucked beside red sandstone, with deep shade and carefully framed views of the land.',
  },
];
